# Site Build Settings

# jekyll-paginate configuration
paginate:            4

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "F I E R R O S   PHOTOGRAPHY"
description:	       "a collection of moments captured in the Sonoran Desert, the Piedmont, and beyond"
author:              "CBF"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
