# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'FLORA',  url: 'FLORA'}
- {name: 'FAUNA', url: 'FAUNA'}
- {name: 'FACES', url: 'FACES'}
- {name: 'FOOD',      url: 'FOOD'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'twitter', link:    'https://twitter.com/paululele'}
#- {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
#- {icon: 'instagram', link:  'https://instagram.com/paululele'}
#- {icon: 'envelope', link:   'mailto:cbfierros95@gmail.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'fresher'
  previous_page: 'older'

# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy...'

# post_date_prefix: 'shared on'
